#!/bin/sh
#
# Script to install manualy Extra OS Templates after new installation
# Author dterweij
#
startopenvz() {
mkdir -p /vz/template/cache
cd /vz/template/cache/
wget https://download.openvz.org/template/precreated/ubuntu-16.04-x86_64.tar.gz
wget https://download.openvz.org/template/precreated/contrib/debian-9.0-x86_64-minimal.tar.gz
cd ~/
yum -y install p7zip.x86_64
git clone https://github.com/taidos/almalinux-deploy.git
rpm -Uvh ~/image-deploy/almalinux-8-x86_64-ez-1.0.0-1BX01.vl7.noarch.rpm
cd ~/almalinux-deploy/image-deploy/
7za -y x "almalinux-8-x86_64.tar.7z.*"
mv almalinux-8-x86_64.tar.gz /vz/template/cache
rf -rf ~/almalinux-deploy
}
#
startxen() {
mkdir -p /home/hypervm/xen/template/
cd /home/hypervm/xen/template/
wget -nd -np -c -r http://download.hypervm-ng.org/download/xentemplates/extra/
}
#
# Check how we were called.
#
case "$1" in
  --xen)
    startxen
    ;;
  --openvz)
    startopenvz
    ;;
  *)
   	echo $"Install extra OSTemplates"
    	echo $"The usage is:"
    	echo $"sh $0 --xen (To install Xen templates)"
    	echo $"sh $0 --openvz (To install OpenVZ templates)"
	exit 1
esac
exit $?
#
# End
